FROM fedora:26
MAINTAINER Dmitry Babokin <dmitry.y.babokin@intel.com>

# !!! Make sure that your docker config provides enough memory to the container,
# otherwise LLVM build may fail, as it will use all the cores available to container.

# Packages required to build ISPC and Clang.
# RUN echo "proxy=http://proxy.yourcompany.com:888" >> /etc/dnf/dnf.conf
RUN dnf install -y vim cmake gcc gcc-c++ git subversion python m4 bison flex patch make ncurses-devel zlib-devel glibc-devel.x86_64 glibc-devel.i686 && \
    dnf clean -y all

# These packages are required if you need to link IPSC with -static.
RUN dnf install -y ncurses-static libstdc++-static zlib-static glibc-static && \
    dnf clean -y all

# If you are behind a proxy, you need to configure git and svn.
#RUN git config --global --add http.proxy http://proxy.yourcompany.com:888
# Initialize svn configs
#RUN svn --version --quiet
#RUN echo "http-proxy-host=proxy.yourcompany.com" >> ~/.subversion/servers
#RUN echo "http-proxy-port=888" >> ~/.subversion/servers

WORKDIR /usr/local/src

# Fork ispc on github and clone *your* fork.
RUN git clone https://github.com/ispc/ispc.git

# This is home for Clang builds
RUN mkdir /usr/local/src/llvm

ENV ISPC_HOME=/usr/local/src/ispc
ENV LLVM_HOME=/usr/local/src/llvm

# If you are going to run test for future platforms, go to
# http://www.intel.com/software/sde and download the latest version,
# extract it, add to path and set SDE_HOME.

WORKDIR /usr/local/src/ispc

# Build Clang 5.0 with all required patches.
# Note self-build options, it's required to build clang and ispc with the same compiler,
# i.e. if clang was built by gcc, you may need to use gcc to build ispc (i.e. run "make gcc"),
# or better do clang selfbuild and use it for ispc build as well (i.e. just "make").
# "rm" are just to keep docker image small.
RUN ./alloy.py -b --version=5.0 --selfbuild && \
    rm -rf $LLVM_HOME/build-5.0 $LLVM_HOME/llvm-5.0 $LLVM_HOME/bin-5.0_temp $LLVM_HOME/build-5.0_temp

ENV PATH=$LLVM_HOME/bin-5.0/bin:$PATH

RUN make -j8
