/*
  Copyright (c) 2024, Intel Corporation

  SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>

#include "bitcode_lib.h"
#include "ispc.h"

#include "llvm/ADT/SmallString.h"
#include <llvm/Support/Path.h>

using namespace ispc;

void printBinaryType() { printf("slim\n"); }

void initializeBinaryType(const char *ISPCExecutableAbsPath) {
    llvm::SmallString<128> includeDir(ISPCExecutableAbsPath);
    llvm::sys::path::remove_filename(includeDir);
    llvm::sys::path::remove_filename(includeDir);
    llvm::SmallString<128> shareDir(includeDir);
    // llvm::sys::path::append(includeDir, "include");
    // lParseInclude(includeDir.c_str());
    llvm::sys::path::append(shareDir, "share", "ispc");
    g->shareDirPath = std::string(shareDir.str());
}

// This file is to be generated by the build system.
#include "bitcode_libs_generated.cpp"
