#  Copyright (c) 2023, Intel Corporation
#  SPDX-License-Identifier: BSD-3-Clause

# This is a template file for the actual snapcraft.yaml that is configured by
# github CI action snap.yml.

name: ispc
base: core22 # ubuntu 22.04
version: '@ISPC_VERSION@'
license: BSD-3-Clause
summary: Compiler for high-performance SIMD programming
description: |
  The Intel® Implicit SPMD Program Compiler (Intel® ISPC) is a compiler for
  writing SPMD (single program multiple data) programs to run on the CPU and
  GPU. The SPMD programming approach is widely known to graphics and GPGPU
  programmers. The main idea behind SPMD is that one writes programs as if they
  were operating on a single data element (a pixel for a pixel shader, for
  example), but then the underlying hardware and runtime system executes
  multiple invocations of the program in parallel with different inputs (the
  values for different pixels, for example).

website: https://ispc.github.io/
contact: aleksei.nurmukhametov@intel.com
issues: https://github.com/ispc/ispc/issues

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  ispc:
    plugin: dump
    source: @ISPC_ARCHIVE@
    stage-packages:
      - libomp-14-dev

apps:
  ispc:
    command: bin/ispc
    plugs:
      - home
