# Copyright 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Lint GitHub Actions workflows
on:
    workflow_dispatch:
    push:
    pull_request:
      paths:
        - '.github/workflows/*'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest@sha256:c6a00dfcb3c7ffb2f22363ded22ce3d789ea4c6a1862b11a2f7716c56c2509af
        with:
          args: -color