# Copyright 2020-2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Check code formatting

permissions: read-all

on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: true

    - name: Install dependencies
      run: |
        echo "APT::Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-retries
        sudo apt-get update
        sudo apt-get install -y clang-format-12 clang-12
        sudo ln -sf /usr/bin/clang-12 /usr/bin/clang
        sudo ln -sf /usr/bin/clang-format-12 /usr/bin/clang-format

    - name: Check format
      run: |
        ./scripts/check_format.sh
