name: Check code formatting

on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        echo "APT::Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-retries
        sudo apt-get update
        sudo apt-get install -y clang-format-10 clang-10
        sudo ln -sf /usr/bin/clang-10 /usr/bin/clang
        sudo ln -sf /usr/bin/clang-format-10 /usr/bin/clang-format

    - name: Check format
      run: |
        ./check_format.sh
