# Copyright (c) 2023, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: (INTERNAL) ISPC update Level-zero

on:
  push:
    paths:
      - '.github/workflows/scripts/internal/update-l0l.sh'
      - '.github/workflows/ispc-ci-internal-update-l0l.yml'
  workflow_dispatch:
  schedule:
    # At 9:00pm on the 3rd and 17th
    - cron: '0 21 3,17 * *'

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  check_version:
    runs-on: 'Linux'
    container: amr-registry.caas.intel.com/ispc/ubuntu:22.04
    steps:
      - name: Checkout core repo for scripts
        uses: actions/checkout@v3

      - name: Checkout core repo for creating PR
        uses: actions/checkout@v3
        with:
          repository: intel-innersource/applications.compilers.ispc.core
          path: ispc
          fetch-depth: 0
          ref: gen
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout Level-Zero
        uses: actions/checkout@v3
        with:
          repository: oneapi-src/level-zero
          path: level-zero
          fetch-depth: 0

      - name: Update Level-zero version
        run: |
            ./.github/workflows/scripts/internal/update-l0l.sh
