# Copyright (c) 2023, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: (INTERNAL) ISPC update vc-intrinsics

on:
  push:
    paths:
      - '.github/workflows/scripts/internal/update-vc-intrinsics.sh'
      - '.github/workflows/ispc-ci-internal-update-vc-intrinsics.yml'
  workflow_dispatch:
  schedule:
    # At 9:00pm on the 3rd and 17th
    - cron: '0 21 3,17 * *'

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  check_version:
    runs-on: 'Linux'
    container: amr-registry.caas.intel.com/ispc/ubuntu:22.04
    steps:
      - name: Checkout core repo for scripts
        uses: actions/checkout@v3

      - name: Checkout core repo for creating PR
        uses: actions/checkout@v3
        with:
          repository: intel-innersource/applications.compilers.ispc.core
          path: ispc
          fetch-depth: 0
          ref: gen
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout vc-intrinsics
        uses: actions/checkout@v3
        with:
          repository: intel/vc-intrinsics
          path: vc-intrinsics

      - name: Checkout internal vc-intrinsics
        uses: actions/checkout@v3
        with:
          repository: intel-innersource/drivers.gpu.compute.vc-intrinsics
          path: vc-intrinsics-int
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Update vc-intrinsics version
        run: |
            ./.github/workflows/scripts/internal/update-vc-intrinsics.sh
