# Nightly Linux run.

name: Linux tests / LLVM 10.0

# Run daily - test sse2-avx2 targets @ -O0/-O1/-O2
on:
  schedule:
    - cron:  '0 7 * * *'

env:
  LLVM_VERSION: "10.0"
  LLVM_REPO: https://github.com/dbabokin/llvm-project
  LLVM_TAR: llvm-10.0.0-ubuntu16.04-Release+Asserts-x86.arm.wasm.tar.xz
  # package name ispc_llvm10_linux

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bison flex libc6-dev-i386 g++-multilib lib32stdc++6 ncurses-dev
        wget $LLVM_REPO/releases/download/llvm-$LLVM_VERSION-ispc-dev/$LLVM_TAR
        tar xvf $LLVM_TAR 
        echo "::add-path::${GITHUB_WORKSPACE}/bin-$LLVM_VERSION/bin"

    - name: Check environment
      run: |
        ./check_env.py
        which -a clang
        cat /proc/cpuinfo

    - name: Build package
      run: |
        mkdir build && cd build
        cmake .. -DISPC_PREPARE_PACKAGE=ON -DISPC_INCLUDE_BENCHMARKS=ON
        make -j4 package

    - name: Sanity testing (make check-all, make test)
      run: |
        cd build
        bin/check_isa
        bin/ispc --support-matrix
        make check-all
        make ispc_benchmarks && make test

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ispc_llvm10_linux
        path: build/ispc-trunk-linux.tar.gz

  linux-test-sse2-i32x4:
    env:
      TARGET: sse2-i32x4
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-sse2-i32x8:
    env:
      TARGET: sse2-i32x8
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-sse4-i32x4:
    env:
      TARGET: sse4-i32x4
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-sse4-i32x8:
    env:
      TARGET: sse4-i32x8
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-sse4-i8x16:
    env:
      TARGET: sse4-i8x16
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-sse4-i16x8:
    env:
      TARGET: sse4-i16x8
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx1-i32x4:
    env:
      TARGET: avx1-i32x4
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx1-i32x8:
    env:
      TARGET: avx1-i32x8
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx1-i32x16:
    env:
      TARGET: avx1-i32x16
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx1-i64x4:
    env:
      TARGET: avx1-i64x4
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx2-i32x4:
    env:
      TARGET: avx2-i32x4
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx2-i32x8:
    env:
      TARGET: avx2-i32x8
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx2-i32x16:
    env:
      TARGET: avx2-i32x16
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx2-i64x4:
    env:
      TARGET: avx2-i64x4
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx2-i8x32:
    env:
      TARGET: avx2-i8x32
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2

  linux-test-avx2-i16x16:
    env:
      TARGET: avx2-i16x16
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_linux_llvm$LLVM_VERIONS
    - name: Unpack
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
    - name: Runtest -O0
      run: |
        ./run_tests.py --target=$TARGET --opt=O0
    - name: Runtest -O1
      run: |
        ./run_tests.py --target=$TARGET --opt=O1
    - name: Runtest -O2
      run: |
        ./run_tests.py --target=$TARGET --opt=O2


