# Nightly Linux run.

name: Nightly Linux tests / LLVM 11.0

# Run daily - test sse2-avx512 targets @ -O0/-O1/-O2
on:
  schedule:
    - cron:  '0 8 * * *'
  push:
    branches:
      - '**test_nightly**'
  workflow_dispatch:

env:
  LLVM_VERSION: "11.0"
  LLVM_REPO: https://github.com/dbabokin/llvm-project
  LLVM_TAR: llvm-11.0.0-ubuntu16.04-Release+Asserts-x86.arm.wasm.tar.xz
  SDE_TAR_NAME: sde-external-8.59.0-2020-10-05-lin

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        echo "APT::Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-retries
        sudo apt-get update
        sudo apt-get install bison flex libc6-dev-i386 g++-multilib lib32stdc++6 ncurses-dev
        wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 $LLVM_REPO/releases/download/llvm-$LLVM_VERSION-ispc-dev/$LLVM_TAR
        tar xf $LLVM_TAR
        echo "${GITHUB_WORKSPACE}/bin-$LLVM_VERSION/bin" >> $GITHUB_PATH

    - name: Check environment
      run: |
        ./check_env.py
        which -a clang
        cat /proc/cpuinfo

    - name: Build package
      run: |
        echo PATH=$PATH
        mkdir build && cd build
        cmake .. -DISPC_PREPARE_PACKAGE=ON -DISPC_INCLUDE_BENCHMARKS=ON
        make -j4 package

    - name: Sanity testing (make check-all, make test)
      run: |
        cd build
        bin/check_isa
        bin/ispc --support-matrix
        make check-all
        make ispc_benchmarks && make test

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ispc_llvm11_linux
        path: build/ispc-trunk-linux.tar.gz

  test:
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        target: [sse2-i32x4, sse2-i32x8,
                 sse4-i8x16, sse4-i16x8, sse4-i32x4, sse4-i32x8,
                 avx1-i32x4, avx1-i32x8, avx1-i32x16, avx1-i64x4,
                 avx2-i8x32, avx2-i16x16, avx2-i32x4, avx2-i32x8, avx2-i32x16, avx2-i64x4,
                 avx512knl-i32x16,
                 avx512skx-i32x8, avx512skx-i32x16, avx512skx-i8x64, avx512skx-i16x32]
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_llvm11_linux
    - name: Install dependencies and unpack artifacts
      run: |
        echo "APT::Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-retries
        sudo apt-get update && sudo apt-get install libc6-dev-i386 g++-multilib lib32stdc++6
        find /usr -name cdefs.h
        wget --user-agent='Mozilla/4.0' https://software.intel.com/content/dam/develop/external/us/en/documents/downloads/$SDE_TAR_NAME.tar.bz2
        tar xf $SDE_TAR_NAME.tar.bz2
        echo "SDE_HOME=$GITHUB_WORKSPACE/$SDE_TAR_NAME" >> $GITHUB_ENV
        tar xf ispc-trunk-linux.tar.gz
        echo "$GITHUB_WORKSPACE/ispc-trunk-linux/bin" >> $GITHUB_PATH
        echo "LLVM_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "ISPC_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Check environment
      run: |
        cat /proc/cpuinfo
    - name: Running tests
      run: |
        echo PATH=$PATH
        ./alloy.py -r --only="stability current -O0 -O1 -O2" --only-targets="${{ matrix.target }}" --time --update-errors=FP
    - name: Upload fail_db.txt
      uses: actions/upload-artifact@v2
      with:
        name: fail_db.${{matrix.target}}.txt
        path: fail_db.txt
    - name: Check
      run: |
        # Print fails to the log.
        git diff
        # Exit with error code is there are fails.
        [ -z "`git diff`" ]
