# Copyright 2022-2023 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Rebuild LLVM 15.0

on:
  push:
    branches:
      - main
      - '**rebuild_llvm**'
    paths:
      - "llvm_patches/*15_0*"
      - "alloy.py"
      - ".github/workflows/rebuild-llvm15.yml"
      - ".github/workflows/reusable.rebuild.yml"
  workflow_dispatch:

jobs:
  llvm15:
    uses: ./.github/workflows/reusable.rebuild.yml
    with:
      version: '15.0'
      full_version: '15.0.7'
      ubuntu: '18.04'
      vs_generator: 'Visual Studio 16 2019'
      vs_version_str: 'vs2019'
