# Copyright 2022 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Rebuild LLVM 13.0

on:
  push:
    branches:
      - main
      - '**rebuild_llvm**'
    paths:
      - "llvm_patches/*13_0*"
      - "alloy.py"
      - ".github/workflows/rebuild-llvm13.yml"
      - ".github/workflows/reusable.rebuild.yml"
  workflow_dispatch:

jobs:
  llvm13:
    uses: ./.github/workflows/reusable.rebuild.yml
    with:
      version: '13.0'
      full_version: '13.0.1'
      ubuntu: '18.04'
      vs_generator: 'Visual Studio 16 2019'
      vs_version_str: 'vs2019'
