name: Rebuild LLVM 12.0

on:
  push:
    branches:
      - main
      - '**rebuild_llvm**'
    paths:
      - "llvm_patches/*12_0*"
      - "alloy.py"
      - ".github/workflows/rebuild-llvm12.yml"
  workflow_dispatch:

jobs:
  # Building LLVM in docker, as using native Ubuntu 16.04 github-hosted image contains newer-than-expected libs and
  # makes the resulting build not usable on other Ubuntu 16.04 images.
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Check environment
      run: |
        cat /proc/cpuinfo

    - name: Build LLVM
      run: |
        cd docker/ubuntu/16.04/cpu_ispc_build
        docker build --tag ispc/ubuntu16.04 --target=llvm_build_only --build-arg REPO=$GITHUB_REPOSITORY --build-arg SHA=$GITHUB_SHA --build-arg LLVM_VERSION=12.0 .

    - name: Pack LLVM
      run: |
        cd docker/ubuntu/16.04/cpu_ispc_build
        docker run ispc/ubuntu16.04
        export CONTAINER=`docker ps --all |head -2 |tail -1 |awk '//{print $1}'`
        sudo docker cp $CONTAINER:/usr/local/src/llvm/bin-12.0 .
        tar cJvf llvm-12.0.1-ubuntu16.04-Release+Asserts-x86.arm.wasm.tar.xz bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12_linux
        path: docker/ubuntu/16.04/cpu_ispc_build/llvm-12.0.1-ubuntu16.04-Release+Asserts-x86.arm.wasm.tar.xz

  linux-build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Check environment
      run: |
        cat /proc/cpuinfo

    - name: Build LLVM
      run: |
        cd docker/ubuntu/16.04/cpu_ispc_build
        docker build --tag ispc/ubuntu16.04 --target=llvm_build_only --build-arg REPO=$GITHUB_REPOSITORY --build-arg SHA=$GITHUB_SHA --build-arg LLVM_VERSION=12.0 --build-arg EXTRA_BUILD_ARG="--llvm-disable-assertions" .

    - name: Pack LLVM
      run: |
        cd docker/ubuntu/16.04/cpu_ispc_build
        docker run ispc/ubuntu16.04
        export CONTAINER=`docker ps --all |head -2 |tail -1 |awk '//{print $1}'`
        sudo docker cp $CONTAINER:/usr/local/src/llvm/bin-12.0 .
        tar cJvf llvm-12.0.1-ubuntu16.04-Release-x86.arm.wasm.tar.xz bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12rel_linux
        path: docker/ubuntu/16.04/cpu_ispc_build/llvm-12.0.1-ubuntu16.04-Release-x86.arm.wasm.tar.xz

  win-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Check environment
      shell: cmd
      run: |
        wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status

    - name: Install dependencies
      shell: cmd
      run: |
        mkdir llvm
        echo LLVM_HOME=%GITHUB_WORKSPACE%\llvm>> %GITHUB_ENV%
        echo ISPC_HOME=%GITHUB_WORKSPACE%>> %GITHUB_ENV%

    - name: Build LLVM
      shell: cmd
      run: |
        python ./alloy.py -b --version=12.0 --verbose
        cd alloy_results* && type alloy_build.log

    - name: Pack LLVM
      shell: cmd
      run: |
        cd llvm
        7z.exe a -t7z llvm-12.0.1-win.vs2019-Release+Asserts-x86.arm.wasm.7z bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12_win
        path: llvm/llvm-12.0.1-win.vs2019-Release+Asserts-x86.arm.wasm.7z

  win-build-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Check environment
      shell: cmd
      run: |
        wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status

    - name: Install dependencies
      shell: cmd
      run: |
        mkdir llvm
        echo LLVM_HOME=%GITHUB_WORKSPACE%\llvm>> %GITHUB_ENV%
        echo ISPC_HOME=%GITHUB_WORKSPACE%>> %GITHUB_ENV%

    - name: Build LLVM
      shell: cmd
      run: |
        python ./alloy.py -b --version=12.0 --verbose --llvm-disable-assertions
        cd alloy_results* && type alloy_build.log

    - name: Pack LLVM
      shell: cmd
      run: |
        cd llvm
        7z.exe a -t7z llvm-12.0.1-win.vs2019-Release-x86.arm.wasm.7z bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12rel_win
        path: llvm/llvm-12.0.1-win.vs2019-Release-x86.arm.wasm.7z

  mac-build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        ls -ald /Applications/Xcode*
        xcrun --show-sdk-path
        # There are several Xcode versions installed.
        # /Applications/Xcode.app is a symlink pointing to the one that needs to be used.
        # But the one, which is currently "selected" doesn't use symlink.
        # We need canonical location to make resulting clang build working on other machines.
        sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
        xcrun --show-sdk-path
        mkdir llvm
        echo "LLVM_HOME=${GITHUB_WORKSPACE}/llvm" >> $GITHUB_ENV
        echo "ISPC_HOME=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

    - name: Check environment
      run: |
        ./check_env.py
        which -a clang
        sysctl -n machdep.cpu.brand_string

    - name: Build LLVM
      run: |
        ./alloy.py -b --version=12.0 --selfbuild --verbose

    - name: Pack LLVM
      run: |
        cd llvm
        tar cJvf llvm-12.0.1-macos10.15-Release+Asserts-x86.arm.wasm.tar.xz bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12_macos
        path: llvm/llvm-12.0.1-macos10.15-Release+Asserts-x86.arm.wasm.tar.xz

  mac-build-release:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        ls -ald /Applications/Xcode*
        xcrun --show-sdk-path
        # There are several Xcode versions installed.
        # /Applications/Xcode.app is a symlink pointing to the one that needs to be used.
        # But the one, which is currently "selected" doesn't use symlink.
        # We need canonical location to make resulting clang build working on other machines.
        sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
        xcrun --show-sdk-path
        mkdir llvm
        echo "LLVM_HOME=${GITHUB_WORKSPACE}/llvm" >> $GITHUB_ENV
        echo "ISPC_HOME=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

    - name: Check environment
      run: |
        ./check_env.py
        which -a clang
        sysctl -n machdep.cpu.brand_string

    - name: Build LLVM
      run: |
        ./alloy.py -b --version=12.0 --selfbuild --verbose --llvm-disable-assertions

    - name: Pack LLVM
      run: |
        cd llvm
        tar cJvf llvm-12.0.1-macos10.15-Release-x86.arm.wasm.tar.xz bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12rel_macos
        path: llvm/llvm-12.0.1-macos10.15-Release-x86.arm.wasm.tar.xz

