name: Rebuild LLVM 12.0

on:
  push:
    branches:
      - main
      - '**rebuild_llvm**'
    paths:
      - "llvm_patches/*12_0*"
      - "alloy.py"
      - ".github/workflows/rebuild-llvm12.yml"
  workflow_dispatch:

jobs:
  # Building LLVM in docker, as using native Ubuntu 18.04 github-hosted image contains newer-than-expected libs and
  # makes the resulting build not usable on other Ubuntu 18.04 images.
  # Doing Linux build in two stages, as self-build is required, but Github Action runners are not always capable
  # to finish the full job in less than 6 hours.
  linux-build-1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Check environment
      run: |
        cat /proc/cpuinfo

    - name: Build LLVM
      run: |
        cd docker/ubuntu/18.04/cpu_ispc_build
        docker buildx create --use
        docker buildx build --tag ispc/ubuntu18.04:stage1 --target=llvm_build_step1 --cache-to=type=local,dest=cache.local --build-arg REPO=$GITHUB_REPOSITORY --build-arg SHA=$GITHUB_SHA --build-arg LLVM_VERSION=12.0 .

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12_linux_stage1_cache
        path: docker/ubuntu/18.04/cpu_ispc_build/cache.local

  linux-build-2:
    needs: [linux-build-1]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Check environment
      run: |
        cat /proc/cpuinfo

    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: llvm12_linux_stage1_cache
        path: docker/ubuntu/18.04/cpu_ispc_build/cache.local

    - name: Build LLVM
      run: |
        cd docker/ubuntu/18.04/cpu_ispc_build
        ls -al
        docker buildx create --use
        docker buildx build --tag ispc/ubuntu18.04:stage2 --target=llvm_build_step2 --cache-from=type=local,src=cache.local --build-arg REPO=$GITHUB_REPOSITORY --build-arg SHA=$GITHUB_SHA --build-arg LLVM_VERSION=12.0 --output=type=tar,dest=result.tar .

    - name: Pack LLVM
      run: |
        cd docker/ubuntu/18.04/cpu_ispc_build
        tar xvf result.tar usr/local/src/llvm
        mv usr/local/src/llvm/bin-12.0 .
        tar cJvf llvm-12.0.1-ubuntu18.04-Release+Asserts-x86.arm.wasm.tar.xz bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12_linux
        path: docker/ubuntu/18.04/cpu_ispc_build/llvm-12.0.1-ubuntu18.04-Release+Asserts-x86.arm.wasm.tar.xz

  linux-build-release-1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Check environment
      run: |
        cat /proc/cpuinfo

    - name: Build LLVM
      run: |
        cd docker/ubuntu/18.04/cpu_ispc_build
        docker buildx create --use
        docker buildx build --tag ispc/ubuntu18.04:stage1 --target=llvm_build_step1 --cache-to=type=local,dest=cache.local --build-arg REPO=$GITHUB_REPOSITORY --build-arg SHA=$GITHUB_SHA --build-arg LLVM_VERSION=12.0 --build-arg EXTRA_BUILD_ARG="--llvm-disable-assertions" .

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12rel_linux_stage1_cache
        path: docker/ubuntu/18.04/cpu_ispc_build/cache.local

  linux-build-release-2:
    needs: [linux-build-release-1]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Check environment
      run: |
        cat /proc/cpuinfo

    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: llvm12rel_linux_stage1_cache
        path: docker/ubuntu/18.04/cpu_ispc_build/cache.local

    - name: Build LLVM
      run: |
        cd docker/ubuntu/18.04/cpu_ispc_build
        ls -al
        docker buildx create --use
        docker buildx build --tag ispc/ubuntu18.04:stage2 --target=llvm_build_step2 --cache-from=type=local,src=cache.local --build-arg REPO=$GITHUB_REPOSITORY --build-arg SHA=$GITHUB_SHA --build-arg LLVM_VERSION=12.0 --build-arg EXTRA_BUILD_ARG="--llvm-disable-assertions" --output=type=tar,dest=result.tar .

    - name: Pack LLVM
      run: |
        cd docker/ubuntu/18.04/cpu_ispc_build
        tar xvf result.tar usr/local/src/llvm
        mv usr/local/src/llvm/bin-12.0 .
        tar cJvf llvm-12.0.1-ubuntu18.04-Release-x86.arm.wasm.tar.xz bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12rel_linux
        path: docker/ubuntu/18.04/cpu_ispc_build/llvm-12.0.1-ubuntu18.04-Release-x86.arm.wasm.tar.xz

  win-build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Check environment
      shell: cmd
      run: |
        wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status

    - name: Install dependencies
      shell: cmd
      run: |
        mkdir llvm
        echo LLVM_HOME=%GITHUB_WORKSPACE%\llvm>> %GITHUB_ENV%
        echo ISPC_HOME=%GITHUB_WORKSPACE%>> %GITHUB_ENV%

    - name: Build LLVM
      shell: cmd
      run: |
        python ./alloy.py -b --version=12.0 --verbose --generator="Visual Studio 16 2019"
        cd alloy_results* && type alloy_build.log

    - name: Pack LLVM
      shell: cmd
      run: |
        cd llvm
        set TAR_BASE_NAME=llvm-12.0.1-win.vs2019-Release+Asserts-x86.arm.wasm
        7z.exe a -ttar -snl %TAR_BASE_NAME%.tar bin-12.0
        7z.exe a -t7z %TAR_BASE_NAME%.tar.7z %TAR_BASE_NAME%.tar

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12_win
        path: llvm/llvm-12.0.1-win.vs2019-Release+Asserts-x86.arm.wasm.tar.7z

  win-build-release:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Check environment
      shell: cmd
      run: |
        wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status

    - name: Install dependencies
      shell: cmd
      run: |
        mkdir llvm
        echo LLVM_HOME=%GITHUB_WORKSPACE%\llvm>> %GITHUB_ENV%
        echo ISPC_HOME=%GITHUB_WORKSPACE%>> %GITHUB_ENV%

    - name: Build LLVM
      shell: cmd
      run: |
        python ./alloy.py -b --version=12.0 --verbose --llvm-disable-assertions --generator="Visual Studio 16 2019"
        cd alloy_results* && type alloy_build.log

    - name: Pack LLVM
      shell: cmd
      run: |
        cd llvm
        set TAR_BASE_NAME=llvm-12.0.1-win.vs2019-Release-x86.arm.wasm
        7z.exe a -ttar -snl %TAR_BASE_NAME%.tar bin-12.0
        7z.exe a -t7z %TAR_BASE_NAME%.tar.7z %TAR_BASE_NAME%.tar

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12rel_win
        path: llvm/llvm-12.0.1-win.vs2019-Release-x86.arm.wasm.tar.7z

  mac-build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        ls -ald /Applications/Xcode*
        xcrun --show-sdk-path
        # There are several Xcode versions installed.
        # /Applications/Xcode.app is a symlink pointing to the one that needs to be used.
        # But the one, which is currently "selected" doesn't use symlink.
        # We need canonical location to make resulting clang build working on other machines.
        sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
        xcrun --show-sdk-path
        mkdir llvm
        echo "LLVM_HOME=${GITHUB_WORKSPACE}/llvm" >> $GITHUB_ENV
        echo "ISPC_HOME=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

    - name: Check environment
      run: |
        ./check_env.py
        which -a clang
        sysctl -n machdep.cpu.brand_string

    - name: Build LLVM
      run: |
        ./alloy.py -b --version=12.0 --selfbuild --verbose

    - name: Pack LLVM
      run: |
        cd llvm
        tar cJvf llvm-12.0.1-macos10.15-Release+Asserts-x86.arm.wasm.tar.xz bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12_macos
        path: llvm/llvm-12.0.1-macos10.15-Release+Asserts-x86.arm.wasm.tar.xz

  mac-build-release:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        ls -ald /Applications/Xcode*
        xcrun --show-sdk-path
        # There are several Xcode versions installed.
        # /Applications/Xcode.app is a symlink pointing to the one that needs to be used.
        # But the one, which is currently "selected" doesn't use symlink.
        # We need canonical location to make resulting clang build working on other machines.
        sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
        xcrun --show-sdk-path
        mkdir llvm
        echo "LLVM_HOME=${GITHUB_WORKSPACE}/llvm" >> $GITHUB_ENV
        echo "ISPC_HOME=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

    - name: Check environment
      run: |
        ./check_env.py
        which -a clang
        sysctl -n machdep.cpu.brand_string

    - name: Build LLVM
      run: |
        ./alloy.py -b --version=12.0 --selfbuild --verbose --llvm-disable-assertions

    - name: Pack LLVM
      run: |
        cd llvm
        tar cJvf llvm-12.0.1-macos10.15-Release-x86.arm.wasm.tar.xz bin-12.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: llvm12rel_macos
        path: llvm/llvm-12.0.1-macos10.15-Release-x86.arm.wasm.tar.xz

